- hosts: localhost
  tasks:
    - name: Creating directory
      file:
        path: ~$USER/.kube
        state: directory

- hosts: master
  tasks:
    - name: Copy config file from Master Node
      fetch:
        src: .kube/config
        dest: ~$USER/.kube/
        flat: yes
        mode: 0644

- hosts: localhost
  tasks:
    - name: Installing dashboard
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

    - name: Creating dashboard user
      shell: kubectl apply -f k8s_scr/dashboard.yaml
    
    - name: Getting token for login purposes
      shell: kubectl get secret -n kubernetes-dashboard $(kubectl get serviceaccount admin-user -n kubernetes-dashboard -o jsonpath="{.secrets[0].name}") -o jsonpath="{.data.token}" | base64 --decode
      register: dash_token

    - name: Use token below to login http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login
      debug:
        msg: "{{ dash_token.stdout_lines }}"
